---
- name: Install NPM
  block:
    - name: Enable software collections
      shell: yum --setopt=tsflags=nodocs -y install centos-release-scl-rh
      become: yes
    - name: Install nodejs 12.x
      shell: yum --enablerepo=centos-sclo-rh-testing -y install rh-nodejs12
      become: yes
  when: deployment_environment_id in ['local_development', 'test', 'stable', 'demo', 'production']

- name: Link npm to usr/local/bin
  block:
      - name: link node, npm, npx to /usr/local/bin/
        file:
          src: /opt/rh/rh-nodejs12/root/bin/{{ item }}
          dest: /usr/local/bin/{{ item }}
          state: link
        with_items:
        - node
        - npm
        - npx
      - name: link node to /usr/local/bin/nodejs
        file:
          src: /opt/rh/rh-nodejs12/root/bin/node
          dest: /usr/local/bin/nodejs
          state: link
  when: deployment_environment_id in ['test', 'stable', 'demo', 'production']