---
- name: Create search app logging folder to {{ directory_log_data }}
  file:
    path: '{{ directory_log_data }}'
    state: directory
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0755'
  become: yes
  tags: etsin-qvain-data-prerequisites

#- name: Ensure required yum packages are installed
#  yum:
#    name:
#      - gcc
#      - gcc-c++
#      - git
#      - curl
#      - vim
#      - zip
#      - unzip
#      - rng-tools
#    state: present, in order not to upgrade any package to an untested version
#    state: 'present'
#  become: yes
#  tags: etsin-qvain-data-prerequisites
