---
- name: Ensure Etsin-Search systemd services are stopped and masked
  systemd:
    name: '{{ item }}'
    state: 'stopped'
    masked: 'yes'
    enabled: 'no'
  with_items:
  - '{{ instance_name_common }}.service'
  - '{{ instance_name_common }}.socket'
  when: delete_deployment
  ignore_errors: yes
  become: yes
  notify: Reload Systemd Daemon
  tags: etsin-qvain-data-delete

- name: Ensure Etsin-Search instance files are deleted
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
  - '{{ repo_path }}'
  - '/etc/systemd/system/{{ instance_name_common }}.service'
  - '/etc/systemd/system/{{ instance_name_common }}.socket'
  - '{{ directory_config }}'
  - '{{ directory_run }}/{{ instance_name_common }}.sock'
  - '{{ nginx_directory_log }}'
  - '{{ directory_venv }}'
  when: delete_deployment
  become: yes
  notify: Reload Systemd Daemon
  tags: etsin-qvain-data-delete
