---
- name: Ensure Etsin user exists
  user:
    name: '{{ application_user }}'
    shell: /bin/bash
  become: yes
  tags: etsin-qvain-users

# - name: Ensure Etsin user bash_aliases is correct
#  template:
#    src: 'fairdata-etsin-bash_aliases.j2'
#    dest: '/home/{{ application_user }}/.bash_aliases'
#    owner: '{{ application_user }}'
#    group: '{{ application_group }}'
#    mode: '0644'
#  become: yes
#  become_user: '{{ application_user }}'
#  tags: etsin-qvain-users

# - name: Ensure Etsin user bash_profile is correct
#  template:
#    src: 'fairdata-etsin-bash_profile.j2'
#    dest: '/home/{{ application_user }}/.bash_profile'
#    owner: '{{ application_user }}'
#    group: '{{ application_group }}'
#    mode: '0644'
#  become: yes
#  become_user: '{{ application_user }}'
#  tags: etsin-qvain-users
