---
- name: Fetch repository etsin-finder-search with git
  git:
    repo: '{{ repo_url_data }}'
    version: '{{ repo_version_data }}'
    force: 'yes'
    key_file: '{{ repo_deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ repo_path_data }}'
  when: repo_install_method == 'pull'
  become: yes
  tags: etsin-qvain-data-repository

- name: Push local Etsin-Search repository
  copy:
    src: '{{ repo_src_data }}'
    dest: '{{ directory_source_root }}'
  when: repo_install_method == 'push'
  tags: etsin-qvain-data-repository

- name: Ensure repository directories exist with correct permissions
  file:
    path: '{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    recurse: 'yes'
    state: 'directory'
  with_items:
  - '{{ repo_path }}'
  - '{{ repo_path_data }}'
  become: yes
  tags: etsin-qvain-data-repository
