---
- name: Ensure that Etsin-Qvain directories exist with correct permissions
  file:
    path: '{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    recurse: 'yes'
    mode: '0755'
    force: 'no'
  with_items:
  - '{{ directory_venv }}'
  - '{{ directory_config }}'
  - '{{ nginx_directory_log }}'
  become: yes
  tags: etsin-qvain-app-configuration

- name: Ensure that Etsin-Qvain

- name: Create logrotation for Etsin-Qvain logs
  template:
    src: 'fairdata-etsin-qvain-logrotation.conf.j2'
    dest: '/etc/logrotate.d/{{ instance_name_common }}'
    mode: '0644'
  become: yes
  tags: etsin-qvain-app-configuration

- name: Install Etsin-Qvain requirements in virtualenv with pip
  pip:
    requirements: '{{ repo_path_app }}/requirements.txt'
    virtualenv: '{{ directory_venv }}'
    virtualenv_command: '{{ python_virtualenv_command }}'
  become: yes
  become_user: '{{ application_user }}'
  notify: Restart Etsin-Qvain
  tags: etsin-qvain-app-configuration

- name: Install Etsin-Qvain app_config
  template:
    src: 'fairdata-etsin-qvain-app-config.j2'
    dest: '{{ application_app_config_path }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0644'
  become: yes
  become_user: '{{ application_user }}'
  tags: etsin-qvain-app-configuration
