---
- name: Get Node 12.x rpm
  shell: 'curl -sL https://rpm.nodesource.com/setup_12.x'
  become: yes
  tags: etsin-qvain-app-nodejs

- name: Install Node 12.x
  block:
    - name: Enable software collections
      shell: yum --setopt=tsflags=nodocs -y install centos-release-scl-rh
      become: yes
    - name: Install nodejs 12.x
      shell: yum --enablerepo=centos-sclo-rh-testing -y install rh-nodejs12
      become: yes
  tags: etsin-qvain-app-nodejs
