---
- name: Include Etsin-Qvain tasks (etsin-finder)
  include_tasks: "main-app.yml"
  when: deploy_app_server
  tags: main-app

- name: Include Etsin-Search tasks (etsin-finder-search)
  include_tasks: "main-data.yml"
  when: deploy_data_server
  tags: main-data
