---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes

- name: Restart Etsin-Qvain
  systemd:
    name: '{{ item }}'
    state: 'restarted'
  with_items:
  - '{{ instance_name_common }}.service'
  - '{{ instance_name_common }}.socket'
  become: yes

- name: Reload Systemd Daemon
  systemd:
    daemon_reload: 'yes'
  become: yes
